pub mod bridge;
pub mod file_explorer;
pub mod plugins;
pub mod state;
pub mod terminal;
pub mod viewport;
pub mod world;

/// Generate TypeScript bindings for the editor's Tauri commands.
///
/// Writes a `bindings.ts` file to `output_path` using `tauri-specta`.
/// Only the commands with fully specta-compatible type signatures are exported
/// (`list_commands` and `run_command`). The generated file should be checked in
/// and kept up to date via `cargo xtask codegen`.
#[cfg(feature = "codegen")]
pub fn generate_bindings(output_path: &str) {
    use tauri_specta::{collect_commands, Builder};

    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            bridge::runner::list_commands,
            bridge::runner::run_command,
        ])
        .export(
            specta_typescript::Typescript::default()
                .header("// This file was generated by `cargo xtask codegen`. Do not edit manually.\n"),
            std::path::Path::new(output_path),
        )
        .expect("Failed to generate TypeScript bindings");
}

use std::sync::{Arc, Mutex};

use bridge::ai_bridge::AiBridgeState;
use bridge::commands;
use bridge::modules::*;
use bridge::registry::CommandRegistry;
use bridge::runner;
use bridge::{
    builtin_schemas::register_builtin_schemas,
    commands::ComponentSchemaState,
    schema_registry::ComponentSchemaRegistry,
};
use file_explorer::{
    get_file_tree, expand_dir, get_git_status, start_file_watch, stop_file_watch,
    open_in_editor, create_file, create_dir, rename_path, delete_path,
};
use terminal::{
    OutputState, TerminalState,
    output::{output_cancel, output_run},
    pty::{terminal_close_tab, terminal_new_tab, terminal_resize, terminal_write},
};

/// Installs a custom WNDPROC that overrides tao's `WM_NCCALCSIZE` handler.
///
/// Root cause of the thin bar at the top:
///   tao keeps `WS_THICKFRAME` for native resize hit-testing and its
///   `WM_NCCALCSIZE` handler calls `calculate_window_insets()` which returns
///   top=1 (one physical pixel) so the OS resize border is reachable.
///   That 1px is the NC area shown as a dark bar above the WebView2.
///   Calling `SWP_FRAMECHANGED` re-triggers tao's handler — making it worse.
///
/// Fix: replace the per-window WNDPROC so we intercept `WM_NCCALCSIZE`.
///   For non-maximized windows we return 0 (client rect = full window rect).
///   For maximized we fall through to tao so it can clamp to the work area
///   and keep the window off the taskbar.
#[cfg(windows)]
static ORIG_WNDPROC: std::sync::atomic::AtomicIsize = std::sync::atomic::AtomicIsize::new(0);

#[cfg(windows)]
unsafe extern "system" fn nc_wndproc(
    hwnd: windows::Win32::Foundation::HWND,
    msg: u32,
    wparam: windows::Win32::Foundation::WPARAM,
    lparam: windows::Win32::Foundation::LPARAM,
) -> windows::Win32::Foundation::LRESULT {
    use windows::Win32::Foundation::LRESULT;
    use windows::Win32::UI::WindowsAndMessaging::{
        CallWindowProcW, DefWindowProcW, GetWindowRect, IsZoomed, WM_NCCALCSIZE, WM_NCHITTEST,
    };

    if msg == WM_NCCALCSIZE && wparam.0 != 0 && !IsZoomed(hwnd).as_bool() {
        // Returning 0 makes the entire window rect the client rect, eliminating
        // tao's 1px top NC inset. WS_THICKFRAME is kept but the NC border area
        // is now 0 px, so WM_NCHITTEST must return resize codes manually.
        return LRESULT(0);
    }

    if msg == WM_NCHITTEST && !IsZoomed(hwnd).as_bool() {
        // With NC area = 0 (from NCCALCSIZE above), Windows never generates
        // HTLEFT/HTRIGHT/etc. on its own — we must emit them when the cursor
        // is within BORDER pixels of any edge.
        let x = (lparam.0 & 0xFFFF) as i16 as i32; // sign-extend for multi-monitor
        let y = ((lparam.0 >> 16) & 0xFFFF) as i16 as i32;
        let mut r = windows::Win32::Foundation::RECT::default();
        if GetWindowRect(hwnd, &mut r).is_ok() {
            const B: i32 = 8; // resize border width (physical pixels)
            let left   = x < r.left   + B;
            let right  = x >= r.right  - B;
            let top    = y < r.top     + B;
            let bottom = y >= r.bottom - B;
            // HTTOPLEFT=13, HTTOPRIGHT=14, HTBOTTOMLEFT=16, HTBOTTOMRIGHT=17
            // HTLEFT=10, HTRIGHT=11, HTTOP=12, HTBOTTOM=15
            let hit: isize = match (left, right, top, bottom) {
                (true,  _,     true,  _)     => 13, // HTTOPLEFT
                (_,     true,  true,  _)     => 14, // HTTOPRIGHT
                (true,  _,     _,     true)  => 16, // HTBOTTOMLEFT
                (_,     true,  _,     true)  => 17, // HTBOTTOMRIGHT
                (true,  _,     _,     _)     => 10, // HTLEFT
                (_,     true,  _,     _)     => 11, // HTRIGHT
                (_,     _,     true,  _)     => 12, // HTTOP
                (_,     _,     _,     true)  => 15, // HTBOTTOM
                _                            =>  0, // not on an edge
            };
            if hit != 0 {
                return LRESULT(hit);
            }
        }
    }

    let orig = ORIG_WNDPROC.load(std::sync::atomic::Ordering::SeqCst);
    if orig != 0 {
        let prev_fn: unsafe extern "system" fn(
            windows::Win32::Foundation::HWND,
            u32,
            windows::Win32::Foundation::WPARAM,
            windows::Win32::Foundation::LPARAM,
        ) -> windows::Win32::Foundation::LRESULT = std::mem::transmute(orig);
        CallWindowProcW(Some(prev_fn), hwnd, msg, wparam, lparam)
    } else {
        DefWindowProcW(hwnd, msg, wparam, lparam)
    }
}

/// Install the NC subclass on an HWND and trigger an immediate frame
/// recalculation so our handler fires before the window is shown.
#[cfg(windows)]
pub(crate) fn install_nc_subclass(hwnd: windows::Win32::Foundation::HWND) {
    use std::sync::atomic::Ordering;
    use windows::Win32::UI::WindowsAndMessaging::{
        SetWindowLongPtrW, SetWindowPos, GWLP_WNDPROC, SWP_FRAMECHANGED, SWP_NOMOVE, SWP_NOSIZE,
        SWP_NOZORDER,
    };
    unsafe {
        let old = SetWindowLongPtrW(hwnd, GWLP_WNDPROC, nc_wndproc as *const () as isize);
        // Store once — all tao windows share the same underlying WNDCLASS proc.
        ORIG_WNDPROC.compare_exchange(0, old, Ordering::SeqCst, Ordering::SeqCst).ok();

        // Trigger WM_NCCALCSIZE now so our handler zeroes the NC area
        // before the window becomes visible.
        SetWindowPos(
            hwnd,
            None,
            0,
            0,
            0,
            0,
            SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER | SWP_FRAMECHANGED,
        )
        .ok();
    }
    tracing::debug!("Installed NC subclass (WM_NCCALCSIZE override)");
}

/// Apply DWM styling to a frameless window on Windows 11:
///   - Rounded corners (DWMWCP_ROUND) matching the OS default
///   - No 1px DWM border (DWMWA_COLOR_NONE)
///
/// Must be called after the window HWND is valid. Safe to call on older Windows
/// versions — DwmSetWindowAttribute is a no-op for unknown attribute IDs.
#[cfg(windows)]
pub(crate) fn apply_dwm_window_style(hwnd: windows::Win32::Foundation::HWND) {
    use std::mem::size_of;
    use windows::Win32::Graphics::Dwm::{
        DwmExtendFrameIntoClientArea, DwmSetWindowAttribute, DWMWA_BORDER_COLOR,
        DWMWA_WINDOW_CORNER_PREFERENCE, DWMWCP_ROUND,
    };

    unsafe {
        // Zero out any DWM frame extension tao may have applied (e.g. from
        // shadow:true in a prior run). A non-zero cyTopHeight is what produces
        // the dark 1-2px bar at the top of a frameless transparent window.
        // MARGINS is [cxLeft, cxRight, cyTop, cyBottom] as four i32s.
        let zero_margins: [i32; 4] = [0, 0, 0, 0];
        let _ = DwmExtendFrameIntoClientArea(hwnd, zero_margins.as_ptr() as *const _);

        // Round corners — Windows 11 DWM DWMWCP_ROUND (value 2).
        // On Win11, DWMWCP_ROUND also re-enables the OS drop-shadow so we do
        // not need shadow:true in tauri.conf.json (which would re-introduce the
        // top-bar artifact via DwmExtendFrameIntoClientArea).
        let corner: u32 = DWMWCP_ROUND.0 as u32;
        let _ = DwmSetWindowAttribute(
            hwnd,
            DWMWA_WINDOW_CORNER_PREFERENCE,
            &corner as *const u32 as *const _,
            size_of::<u32>() as u32,
        );

        // Remove the 1px DWM border (DWMWA_COLOR_NONE = 0xFFFFFFFE).
        let no_border: u32 = 0xFFFFFFFE;
        let _ = DwmSetWindowAttribute(
            hwnd,
            DWMWA_BORDER_COLOR,
            &no_border as *const u32 as *const _,
            size_of::<u32>() as u32,
        );
    }

    tracing::debug!("Applied DWM rounded corners + no border + zeroed frame extension");
}

pub fn run() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "silmaril_editor=debug,engine_renderer=debug,warn".into()),
        )
        .init();

    // Install a panic hook that logs to tracing before the default handler runs
    let default_hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(move |info| {
        let location = info
            .location()
            .map(|l| format!("{}:{}:{}", l.file(), l.line(), l.column()))
            .unwrap_or_else(|| "unknown".into());
        let payload = if let Some(s) = info.payload().downcast_ref::<&str>() {
            s.to_string()
        } else if let Some(s) = info.payload().downcast_ref::<String>() {
            s.clone()
        } else {
            "unknown panic".into()
        };
        tracing::error!(location = %location, payload = %payload, "PANIC in Silmaril Editor");
        // Also write to stderr in case tracing subscriber is broken
        eprintln!("[CRASH] PANIC at {location}: {payload}");
        default_hook(info);
    }));

    // On Windows, install a vectored exception handler to catch SEH
    // exceptions (access violations, etc.) that bypass Rust's panic
    // mechanism.  This logs the crash before the process terminates.
    #[cfg(windows)]
    unsafe {
        use windows::Win32::System::Diagnostics::Debug::{
            AddVectoredExceptionHandler, EXCEPTION_POINTERS,
        };
        unsafe extern "system" fn crash_handler(info: *mut EXCEPTION_POINTERS) -> i32 {
            if info.is_null() {
                return 0; // EXCEPTION_CONTINUE_SEARCH
            }
            let record = (*info).ExceptionRecord;
            if record.is_null() {
                return 0;
            }
            let code = (*record).ExceptionCode.0 as u32;
            // Only log fatal exceptions, not benign ones
            if code == 0xC0000005  // ACCESS_VIOLATION
                || code == 0xC0000409  // STATUS_STACK_BUFFER_OVERRUN
                || code == 0xC0000374  // HEAP_CORRUPTION
                || code == 0xC00000FD
            // STACK_OVERFLOW
            {
                let addr = (*record).ExceptionAddress as usize;
                eprintln!("[CRASH] SEH exception 0x{code:08X} at address 0x{addr:X}");
            }
            0 // EXCEPTION_CONTINUE_SEARCH
        }
        AddVectoredExceptionHandler(0, Some(crash_handler));
    }

    tracing::info!("Silmaril Editor starting");

    let mut schema_registry = ComponentSchemaRegistry::new();
    register_builtin_schemas(&mut schema_registry);

    let (mut registry, registry_rx) = CommandRegistry::new();
    registry.register_module(&FileModule);
    registry.register_module(&EditModule);
    registry.register_module(&ViewModule);
    registry.register_module(&SceneModule);
    registry.register_module(&AssetModule);
    registry.register_module(&BuildModule);
    registry.register_module(&ViewportModule);
    registry.register_module(&TemplateModule);
    registry.register_module(&UserCommandsModule);
    registry.register_module(&EditorCoreModule);
    registry.register_module(&ProjectModule);
    let ai_bridge_state = AiBridgeState::new(registry_rx.clone());
    let registry = Arc::new(Mutex::new(registry));

    let asset_manager = Arc::new(engine_assets::AssetManager::new());
    crate::state::primitives::register_primitives(&asset_manager);

    tauri::Builder::default()
        .plugin(tauri_plugin_store::Builder::default().build())
        .plugin(tauri_plugin_dialog::init())
        .manage(commands::NativeViewportState::new())
        .manage(Mutex::new(bridge::template_commands::EditorState::new()))
        .manage(registry)
        .manage(ai_bridge_state)
        .manage(file_explorer::FileWatcherState::new())
        .manage(ComponentSchemaState(std::sync::Mutex::new(schema_registry)))
        .manage(commands::ProjectState::new())
        .manage(TerminalState::new())
        .manage(OutputState::new())
        .manage(crate::state::SceneWorldState::new())
        .manage(crate::state::AssetManagerState(asset_manager))
        .invoke_handler(tauri::generate_handler![
            commands::get_editor_state,
            commands::get_component_schemas,
            commands::set_component_field,
            commands::open_project,
            commands::open_project_dialog,
            commands::scan_project_entities,
            commands::create_native_viewport,
            commands::resize_native_viewport,
            commands::destroy_native_viewport,
            commands::set_viewport_visible,
            commands::viewport_camera_orbit,
            commands::viewport_camera_pan,
            commands::viewport_camera_zoom,
            commands::viewport_camera_reset,
            commands::viewport_set_grid_visible,
            commands::viewport_camera_set_orientation,
            commands::viewport_set_projection,
            commands::create_popout_window,
            commands::dock_panel_back,
            commands::check_dock_proximity,
            commands::window_minimize,
            commands::window_toggle_maximize,
            commands::window_close,
            commands::window_start_drag,
            commands::window_start_resize,
            commands::start_dock_drag,
            commands::broadcast_settings,
            get_file_tree,
            expand_dir,
            get_git_status,
            start_file_watch,
            stop_file_watch,
            open_in_editor,
            create_file,
            create_dir,
            rename_path,
            delete_path,
            runner::list_commands,
            runner::run_command,
            commands::scan_assets,
            bridge::template_commands::template_open,
            bridge::template_commands::template_close,
            bridge::template_commands::template_execute,
            bridge::template_commands::template_undo,
            bridge::template_commands::template_redo,
            bridge::template_commands::template_history,
            commands::add_component,
            commands::remove_component,
            terminal_new_tab,
            terminal_write,
            terminal_resize,
            terminal_close_tab,
            output_run,
            output_cancel,
            commands::create_entity,
            commands::delete_entity,
            commands::create_entity_child,
            bridge::gizmo_commands::gizmo_hit_test,
            bridge::gizmo_commands::gizmo_drag,
            bridge::gizmo_commands::gizmo_drag_end,
            bridge::gizmo_commands::set_gizmo_mode,
            bridge::gizmo_commands::gizmo_hover_test,
            bridge::gizmo_commands::set_hovered_gizmo_axis,
            bridge::ai_bridge::ai_server_start,
            bridge::ai_bridge::ai_server_stop,
            bridge::ai_bridge::ai_server_status,
            bridge::ai_bridge::ai_grant_permission,
            bridge::ai_bridge::ai_scene_response,
            commands::set_selected_entity,
            commands::assign_mesh,
        ])
        .setup(move |app| {
            bridge::registry_bridge::setup_registry_watch(registry_rx, app.handle().clone());

            use tauri::Manager;
            if let Some(main_window) = app.get_webview_window("main") {
                // Set window + webview background to fully transparent
                let transparent = tauri::utils::config::Color(0, 0, 0, 0);
                let _ = main_window.set_background_color(Some(transparent));

                // On Windows, disable clip-children so the Vulkan child window
                // (behind the webview) can show through transparent regions.
                // Also apply DWM styling: rounded corners + no border.
                #[cfg(windows)]
                {
                    use windows::Win32::UI::WindowsAndMessaging::*;

                    let hwnd = main_window.hwnd().unwrap();
                    unsafe {
                        let style = GetWindowLongW(hwnd, GWL_STYLE);
                        // Strip WS_CAPTION + WS_SYSMENU (visual chrome) and
                        // WS_CLIPCHILDREN (so Vulkan DXGI shows through WebView2).
                        // Keep WS_THICKFRAME — needed for resize hit-testing and
                        // our NC subclass relies on it being present.
                        SetWindowLongW(
                            hwnd,
                            GWL_STYLE,
                            style
                                & !(WS_CAPTION.0 as i32)
                                & !(WS_SYSMENU.0 as i32)
                                & !(WS_CLIPCHILDREN.0 as i32),
                        );
                        tracing::info!("Stripped WS_CAPTION/WS_SYSMENU/WS_CLIPCHILDREN");
                    }
                    // Override tao's WM_NCCALCSIZE to eliminate the 1px NC top bar.
                    // This also triggers SWP_FRAMECHANGED so our handler fires now.
                    install_nc_subclass(hwnd);
                    apply_dwm_window_style(hwnd);
                }
            }
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error running Silmaril Editor");
}
