// Allow dead code for now - these functions are part of the codegen API
// and will be used when module management commands are implemented
#![allow(dead_code)]

use anyhow::{Context, Result};
use std::path::Path;

/// Update module exports in a mod.rs file
///
/// This function adds or updates exports for a component or system in the corresponding
/// mod.rs file. It will:
/// - Create mod.rs if it doesn't exist
/// - Add a module declaration (pub mod {snake_name};)
/// - Add a re-export (pub use {snake_name}::{ItemName};)
/// - Maintain alphabetical sorting
/// - Avoid duplicates
///
/// # Arguments
/// * `target_dir` - Directory containing the mod.rs file (e.g., shared/src/components/)
/// * `item_name` - Name of the item in PascalCase (e.g., "Health")
/// * `item_type` - Type of item: "component" or "system"
///
/// # Example
/// ```no_run
/// use std::path::Path;
/// use silm::codegen::update_module_exports;
///
/// let components_dir = Path::new("shared/src/components");
/// update_module_exports(components_dir, "Health", "component")?;
/// # Ok::<(), anyhow::Error>(())
/// ```
pub fn update_module_exports(target_dir: &Path, item_name: &str, item_type: &str) -> Result<()> {
    // Create target directory if it doesn't exist
    if !target_dir.exists() {
        std::fs::create_dir_all(target_dir)
            .with_context(|| format!("Failed to create directory: {:?}", target_dir))?;
    }

    let mod_file = target_dir.join("mod.rs");
    let snake_name = to_snake_case(item_name);

    // Read existing mod.rs or create new with header
    let content = if mod_file.exists() {
        std::fs::read_to_string(&mod_file)
            .with_context(|| format!("Failed to read mod.rs at {:?}", mod_file))?
    } else {
        create_mod_header(item_type)
    };

    // Check if already exported
    let mod_line = format!("pub mod {};", snake_name);
    if content.contains(&mod_line) {
        // Already exported, nothing to do
        return Ok(());
    }

    // Parse the content into sections
    let (header, mut mod_declarations, mut re_exports) = parse_mod_file(&content);

    // Add new module declaration with timestamp
    let timestamp = chrono::Utc::now().to_rfc3339();
    let new_mod_line = format!("pub mod {};  // Added: {}", snake_name, timestamp);
    mod_declarations.push(new_mod_line);

    // Add new re-export
    let new_export = format!("pub use {}::{};", snake_name, item_name);
    re_exports.push(new_export);

    // Sort declarations and exports alphabetically
    mod_declarations.sort();
    re_exports.sort();

    // Reconstruct the file
    let mut new_content = String::new();
    new_content.push_str(&header);

    if !mod_declarations.is_empty() {
        new_content.push('\n');
        for decl in &mod_declarations {
            new_content.push_str(decl);
            new_content.push('\n');
        }
    }

    if !re_exports.is_empty() {
        new_content.push('\n');
        for export in &re_exports {
            new_content.push_str(export);
            new_content.push('\n');
        }
    }

    // Write back to file
    std::fs::write(&mod_file, new_content)
        .with_context(|| format!("Failed to write mod.rs at {:?}", mod_file))?;

    Ok(())
}

/// Convert PascalCase to snake_case
///
/// # Examples
/// ```
/// use silm::codegen::to_snake_case;
///
/// assert_eq!(to_snake_case("Health"), "health");
/// assert_eq!(to_snake_case("PlayerState"), "player_state");
/// assert_eq!(to_snake_case("MeshRenderer2D"), "mesh_renderer2_d");
/// ```
pub fn to_snake_case(name: &str) -> String {
    let mut result = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_lowercase().next().unwrap());
    }
    result
}

/// Create the default header for a mod.rs file
fn create_mod_header(item_type: &str) -> String {
    format!(
        "// Auto-generated by silm CLI - DO NOT EDIT MANUALLY\n\
         // Run `silm add {}` to add new {}s\n",
        item_type, item_type
    )
}

/// Parse a mod.rs file into its components: header, module declarations, and re-exports
fn parse_mod_file(content: &str) -> (String, Vec<String>, Vec<String>) {
    let mut header = String::new();
    let mut mod_declarations = Vec::new();
    let mut re_exports = Vec::new();

    let mut in_header = true;

    for line in content.lines() {
        let trimmed = line.trim();

        // Header: comment lines at the beginning
        if in_header && (trimmed.starts_with("//") || trimmed.is_empty()) {
            header.push_str(line);
            header.push('\n');
        } else {
            in_header = false;

            // Strip inline comment before checking suffix
            let bare = trimmed.splitn(2, "//").next().unwrap_or("").trim();

            // Module declarations
            if bare.starts_with("pub mod ") && bare.ends_with(';') {
                mod_declarations.push(line.to_string());
            }
            // Re-exports
            else if bare.starts_with("pub use ") && bare.ends_with(';') {
                re_exports.push(line.to_string());
            }
            // Ignore other lines (blank lines, etc.)
        }
    }

    // Remove trailing newline from header if present
    if header.ends_with('\n') {
        header.pop();
    }

    (header, mod_declarations, re_exports)
}

#[cfg(test)]
mod tests {
    use super::*;

    mod to_snake_case_tests {
        use super::*;

        #[test]
        fn test_simple() {
            assert_eq!(to_snake_case("Health"), "health");
        }

        #[test]
        fn test_compound() {
            assert_eq!(to_snake_case("PlayerState"), "player_state");
        }

        #[test]
        fn test_with_numbers() {
            assert_eq!(to_snake_case("MeshRenderer2D"), "mesh_renderer2_d");
        }

        #[test]
        fn test_single_letter() {
            assert_eq!(to_snake_case("A"), "a");
        }

        #[test]
        fn test_multiple_caps() {
            assert_eq!(to_snake_case("HTTPServer"), "h_t_t_p_server");
        }
    }

    mod parse_mod_file_tests {
        use super::*;

        #[test]
        fn test_parse_empty() {
            let (header, mods, exports) = parse_mod_file("");
            assert!(header.is_empty());
            assert!(mods.is_empty());
            assert!(exports.is_empty());
        }

        #[test]
        fn test_parse_header_only() {
            let content = "// Auto-generated by silm CLI\n// Do not edit\n";
            let (header, mods, exports) = parse_mod_file(content);
            assert_eq!(header, "// Auto-generated by silm CLI\n// Do not edit");
            assert!(mods.is_empty());
            assert!(exports.is_empty());
        }

        #[test]
        fn test_parse_with_declarations() {
            let content = "// Header\n\npub mod health;\npub mod velocity;\n";
            let (header, mods, exports) = parse_mod_file(content);
            assert_eq!(header, "// Header\n");
            assert_eq!(mods.len(), 2);
            assert!(mods.contains(&"pub mod health;".to_string()));
            assert!(mods.contains(&"pub mod velocity;".to_string()));
            assert!(exports.is_empty());
        }

        #[test]
        fn test_parse_with_exports() {
            let content = "// Header\n\npub use health::Health;\npub use velocity::Velocity;\n";
            let (header, mods, exports) = parse_mod_file(content);
            assert_eq!(header, "// Header\n");
            assert!(mods.is_empty());
            assert_eq!(exports.len(), 2);
            assert!(exports.contains(&"pub use health::Health;".to_string()));
            assert!(exports.contains(&"pub use velocity::Velocity;".to_string()));
        }

        #[test]
        fn test_parse_complete_file() {
            let content = "// Auto-generated\n// Do not edit\n\n\
                           pub mod health;  // Added: 2026-01-01\n\
                           pub mod velocity;\n\n\
                           pub use health::Health;\n\
                           pub use velocity::Velocity;\n";
            let (header, mods, exports) = parse_mod_file(content);
            assert_eq!(header, "// Auto-generated\n// Do not edit\n");
            assert_eq!(mods.len(), 2);
            assert_eq!(exports.len(), 2);
        }
    }

    mod create_mod_header_tests {
        use super::*;

        #[test]
        fn test_component_header() {
            let header = create_mod_header("component");
            assert!(header.contains("silm add component"));
            assert!(header.contains("Auto-generated"));
        }

        #[test]
        fn test_system_header() {
            let header = create_mod_header("system");
            assert!(header.contains("silm add system"));
            assert!(header.contains("Auto-generated"));
        }
    }
}
