use anyhow::Result;
use silm::codegen::module_exports::{to_snake_case, update_module_exports};
use std::path::PathBuf;
use tempfile::TempDir;

/// Helper function to create a temporary directory for testing
fn create_temp_dir() -> TempDir {
    TempDir::new().expect("Failed to create temp dir")
}

/// Helper function to read file contents
fn read_file(path: &PathBuf) -> String {
    std::fs::read_to_string(path).expect("Failed to read file")
}

#[test]
fn test_create_new_mod_rs() -> Result<()> {
    let temp_dir = create_temp_dir();
    let components_dir = temp_dir.path().join("src/components");

    // Update module exports (should create mod.rs)
    update_module_exports(&components_dir, "Health", "component")?;

    // Verify mod.rs was created
    let mod_file = components_dir.join("mod.rs");
    assert!(mod_file.exists(), "mod.rs should be created");

    // Verify contents
    let content = read_file(&mod_file);
    assert!(content.contains("// Auto-generated by silm CLI"));
    assert!(content.contains("pub mod health;"));
    assert!(content.contains("pub use health::Health;"));
    assert!(content.contains("// Added:"));

    Ok(())
}

#[test]
fn test_update_existing_mod_rs() -> Result<()> {
    let temp_dir = create_temp_dir();
    let components_dir = temp_dir.path().join("src/components");
    std::fs::create_dir_all(&components_dir)?;

    // Create initial mod.rs with one component
    let mod_file = components_dir.join("mod.rs");
    std::fs::write(
        &mod_file,
        "// Auto-generated by silm CLI\n\n\
         pub mod health;  // Added: 2026-01-01\n\n\
         pub use health::Health;\n",
    )?;

    // Add a second component
    update_module_exports(&components_dir, "Velocity", "component")?;

    // Verify both components are present
    let content = read_file(&mod_file);
    assert!(content.contains("pub mod health;"));
    assert!(content.contains("pub mod velocity;"));
    assert!(content.contains("pub use health::Health;"));
    assert!(content.contains("pub use velocity::Velocity;"));

    Ok(())
}

#[test]
fn test_no_duplicate_exports() -> Result<()> {
    let temp_dir = create_temp_dir();
    let components_dir = temp_dir.path().join("src/components");
    std::fs::create_dir_all(&components_dir)?;

    // Add component twice
    update_module_exports(&components_dir, "Health", "component")?;
    update_module_exports(&components_dir, "Health", "component")?;

    // Verify only one export
    let mod_file = components_dir.join("mod.rs");
    let content = read_file(&mod_file);

    let mod_count = content.matches("pub mod health;").count();
    let use_count = content.matches("pub use health::Health;").count();

    assert_eq!(mod_count, 1, "Should have exactly one module declaration");
    assert_eq!(use_count, 1, "Should have exactly one re-export");

    Ok(())
}

#[test]
fn test_alphabetical_sorting_modules() -> Result<()> {
    let temp_dir = create_temp_dir();
    let components_dir = temp_dir.path().join("src/components");
    std::fs::create_dir_all(&components_dir)?;

    // Add components in non-alphabetical order
    update_module_exports(&components_dir, "Velocity", "component")?;
    update_module_exports(&components_dir, "Health", "component")?;
    update_module_exports(&components_dir, "Armor", "component")?;

    // Verify they are sorted
    let mod_file = components_dir.join("mod.rs");
    let content = read_file(&mod_file);

    // Find positions of each module declaration
    let armor_pos = content.find("pub mod armor;").unwrap();
    let health_pos = content.find("pub mod health;").unwrap();
    let velocity_pos = content.find("pub mod velocity;").unwrap();

    assert!(armor_pos < health_pos, "armor should come before health");
    assert!(health_pos < velocity_pos, "health should come before velocity");

    Ok(())
}

#[test]
fn test_alphabetical_sorting_exports() -> Result<()> {
    let temp_dir = create_temp_dir();
    let components_dir = temp_dir.path().join("src/components");
    std::fs::create_dir_all(&components_dir)?;

    // Add components in non-alphabetical order
    update_module_exports(&components_dir, "Velocity", "component")?;
    update_module_exports(&components_dir, "Health", "component")?;
    update_module_exports(&components_dir, "Armor", "component")?;

    // Verify re-exports are sorted
    let mod_file = components_dir.join("mod.rs");
    let content = read_file(&mod_file);

    // Find positions of each re-export
    let armor_pos = content.find("pub use armor::Armor;").unwrap();
    let health_pos = content.find("pub use health::Health;").unwrap();
    let velocity_pos = content.find("pub use velocity::Velocity;").unwrap();

    assert!(armor_pos < health_pos, "armor export should come before health");
    assert!(
        health_pos < velocity_pos,
        "health export should come before velocity"
    );

    Ok(())
}

#[test]
fn test_preserves_header() -> Result<()> {
    let temp_dir = create_temp_dir();
    let components_dir = temp_dir.path().join("src/components");
    std::fs::create_dir_all(&components_dir)?;

    // Add first component
    update_module_exports(&components_dir, "Health", "component")?;

    let mod_file = components_dir.join("mod.rs");
    let initial_content = read_file(&mod_file);

    // Add second component
    update_module_exports(&components_dir, "Velocity", "component")?;

    let updated_content = read_file(&mod_file);

    // Verify header is still present
    assert!(updated_content.contains("// Auto-generated by silm CLI"));
    assert!(updated_content.contains("// Run `silm add component`"));

    Ok(())
}

#[test]
fn test_system_type() -> Result<()> {
    let temp_dir = create_temp_dir();
    let systems_dir = temp_dir.path().join("src/systems");

    // Add a system (not a component)
    update_module_exports(&systems_dir, "health_regen", "system")?;

    // Verify header mentions systems
    let mod_file = systems_dir.join("mod.rs");
    let content = read_file(&mod_file);

    assert!(content.contains("// Run `silm add system`"));
    assert!(content.contains("pub mod health_regen;"));
    assert!(content.contains("pub use health_regen::health_regen;"));

    Ok(())
}

#[test]
fn test_creates_parent_directories() -> Result<()> {
    let temp_dir = create_temp_dir();
    let deep_dir = temp_dir
        .path()
        .join("src/deeply/nested/components/somewhere");

    // This should create all parent directories
    update_module_exports(&deep_dir, "Health", "component")?;

    // Verify directory structure was created
    assert!(deep_dir.exists());
    assert!(deep_dir.join("mod.rs").exists());

    Ok(())
}

#[test]
fn test_pascal_to_snake_case() {
    assert_eq!(to_snake_case("Health"), "health");
    assert_eq!(to_snake_case("PlayerState"), "player_state");
    assert_eq!(to_snake_case("MeshRenderer2D"), "mesh_renderer2_d");
    assert_eq!(to_snake_case("HTTPSConnection"), "h_t_t_p_s_connection");
}

#[test]
fn test_multiple_components_maintain_order() -> Result<()> {
    let temp_dir = create_temp_dir();
    let components_dir = temp_dir.path().join("src/components");
    std::fs::create_dir_all(&components_dir)?;

    // Add components
    update_module_exports(&components_dir, "Zebra", "component")?;
    update_module_exports(&components_dir, "Alpha", "component")?;
    update_module_exports(&components_dir, "Middle", "component")?;

    // Verify sorting is maintained
    let mod_file = components_dir.join("mod.rs");
    let content = read_file(&mod_file);

    let alpha_pos = content.find("pub mod alpha;").unwrap();
    let middle_pos = content.find("pub mod middle;").unwrap();
    let zebra_pos = content.find("pub mod zebra;").unwrap();

    assert!(alpha_pos < middle_pos);
    assert!(middle_pos < zebra_pos);

    Ok(())
}

#[test]
fn test_timestamp_added() -> Result<()> {
    let temp_dir = create_temp_dir();
    let components_dir = temp_dir.path().join("src/components");

    update_module_exports(&components_dir, "Health", "component")?;

    let mod_file = components_dir.join("mod.rs");
    let content = read_file(&mod_file);

    // Verify timestamp is present (should be in ISO 8601 format)
    assert!(
        content.contains("// Added: 20"),
        "Should contain a timestamp starting with '// Added: 20'"
    );

    Ok(())
}

#[test]
fn test_handles_empty_existing_mod_rs() -> Result<()> {
    let temp_dir = create_temp_dir();
    let components_dir = temp_dir.path().join("src/components");
    std::fs::create_dir_all(&components_dir)?;

    // Create empty mod.rs
    let mod_file = components_dir.join("mod.rs");
    std::fs::write(&mod_file, "")?;

    // Add component
    update_module_exports(&components_dir, "Health", "component")?;

    let content = read_file(&mod_file);
    assert!(content.contains("pub mod health;"));
    assert!(content.contains("pub use health::Health;"));

    Ok(())
}

#[test]
fn test_complex_names() -> Result<()> {
    let temp_dir = create_temp_dir();
    let components_dir = temp_dir.path().join("src/components");

    // Test various complex names
    update_module_exports(&components_dir, "HTTPSConnection", "component")?;
    update_module_exports(&components_dir, "AI2DRenderer", "component")?;

    let mod_file = components_dir.join("mod.rs");
    let content = read_file(&mod_file);

    assert!(content.contains("pub mod h_t_t_p_s_connection;"));
    assert!(content.contains("pub use h_t_t_p_s_connection::HTTPSConnection;"));
    assert!(content.contains("pub mod a_i2_d_renderer;"));
    assert!(content.contains("pub use a_i2_d_renderer::AI2DRenderer;"));

    Ok(())
}
